# fly.toml app configuration file generated for test-project-thbjja on 2025-11-20T15:37:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "test-project-thbjja"
primary_region = "cdg"

[processes]
worker = "node index.js"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"

